# Generated by Django 3.1.7 on 2021-04-25 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210425_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelfile',
            name='name',
            field=models.TextField(default=12),
            preserve_default=False,
        ),
    ]
