# Generated by Django 3.1.7 on 2021-04-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_modelfile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelfile',
            name='token',
            field=models.TextField(default=12),
            preserve_default=False,
        ),
    ]
